"""Regenerate repo-catalog.md from the repos themselves.

Facts (purpose, entry points, dependencies, library modules used, couplings) come
from manifests and an import scan. Hand-written ``**Note...`` lines in an existing
catalog are carried over per repo, so verified annotations survive a regenerate.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from datetime import date
from pathlib import Path

from fleet_cli.repos import LIBRARY, PROJECTS, Repo

_DOTTED = re.compile(r"^\s*(?:from|import)\s+local_first_common\.(\w+)", re.MULTILINE)
_FROM_PKG = re.compile(
    r"^[ \t]*from[ \t]+local_first_common[ \t]+import[ \t]+(?:\(([\w\s,]+)\)|([\w \t,]+))", re.MULTILINE
)
_IMPORT = re.compile(r"^\s*(?:from|import)\s+(\w+)", re.MULTILINE)
_HEADING = re.compile(r"^### (\S+)\s*$")


@dataclass
class Entry:
    name: str
    location: str
    kind: str
    description: str
    entry_points: dict[str, str]
    dependencies: list[str]
    library_modules: list[str]
    couplings: list[str] = field(default_factory=list)
    remote: str = ""
    last_commit: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


def library_module_names(library: Path) -> set[str]:
    pkg = library / "src" / "local_first_common"
    return {p.stem for p in pkg.glob("*.py") if p.stem != "__init__"} | {
        p.parent.name for p in pkg.glob("*/__init__.py")
    }


def library_modules_used(source: str, known: set[str]) -> list[str]:
    used = set(_DOTTED.findall(source))
    for paren, bare in _FROM_PKG.findall(source):
        used |= {n.strip() for n in (paren or bare).split(",") if n.strip() in known}
    return sorted(used)


def build_entries(repos: list[Repo], root: Path = PROJECTS) -> list[Entry]:
    known = library_module_names(root / "local-first" / LIBRARY)
    owner = {pkg: r.name for r in repos for pkg in r.packages}
    entries = []
    for r in repos:
        imported = set(_IMPORT.findall(r.source_text)) if r.is_python else set()
        siblings = {owner[m] for m in imported if m in owner and owner[m] not in (r.name, LIBRARY)}
        couplings = sorted(siblings | set(r.path_dependencies))
        date_, subject = r.last_commit
        entries.append(Entry(
            name=r.name,
            location=str(r.path.relative_to(root)),
            kind="python" if r.is_python else "node" if r.package_json else "other",
            description=r.description,
            entry_points=r.entry_points,
            dependencies=[d for d in r.dependencies if d != LIBRARY],
            library_modules=library_modules_used(r.source_text, known) if r.is_python else [],
            couplings=couplings,
            remote=r.remote,
            last_commit=f"{date_} {subject}".strip(),
        ))
    return entries


def extract_notes(markdown: str) -> dict[str, list[str]]:
    """``**Note...`` lines under each ``### repo`` heading of an existing catalog."""
    notes: dict[str, list[str]] = {}
    current = None
    for line in markdown.splitlines():
        if m := _HEADING.match(line):
            current = m.group(1)
        elif line.startswith("## "):
            current = None
        elif current and line.startswith("**Note"):
            notes.setdefault(current, []).append(line)
    return notes


def _render_entry(e: Entry, notes: list[str]) -> list[str]:
    eps = ", ".join(f"`{k}` (`{v}`)" for k, v in e.entry_points.items()) or "none"
    lines = [
        f"### {e.name}",
        f"**Path:** `{e.location}`",
        f"**Purpose:** {e.description or '_no description in manifest_'}",
        f"**Entry points:** {eps}",
        f"**Dependencies:** {', '.join(e.dependencies) or 'none'}",
    ]
    if e.kind == "python" and e.name != LIBRARY:
        lines.append(f"**{LIBRARY} usage:** {', '.join(f'`{m}`' for m in e.library_modules) or 'none'}")
    if e.couplings:
        lines.append(f"**Couples to:** {', '.join(e.couplings)}")
    lines.append(f"**Remote:** {e.remote or '**none**'}  ")
    lines.append(f"**Last commit:** {e.last_commit or 'none'}")
    return [*lines, *notes, ""]


def render_markdown(entries: list[Entry], notes: dict[str, list[str]], generated: date) -> str:
    library = [e for e in entries if e.name == LIBRARY]
    top = [e for e in entries if "/" not in e.location]
    fleet = [e for e in entries if e.location.startswith("local-first/") and e.name != LIBRARY]
    out = [
        "# Repo Catalog",
        "",
        (
            "Every repo under `~/projects` and `~/projects/local-first`. Generated by `fleet catalog`; "
            "facts come from each repo's manifest and an import scan. Add hand-verified context as "
            "`**Note ...**` lines under a repo; they are kept on regenerate."
        ),
        "",
        f"Generated: {generated.isoformat()}. {len(entries)} repos.",
        "",
    ]
    for title, group in (
        ("Shared library", library),
        ("Top-level repos (`~/projects`)", top),
        ("`local-first/` repos", fleet),
    ):
        if group:
            out += ["---", "", f"## {title}", ""]
            for e in group:
                out += _render_entry(e, notes.get(e.name, []))
    coupled = [e for e in entries if e.couplings]
    if coupled:
        out += ["---", "", f"## Cross-repo couplings (beyond {LIBRARY})", ""]
        out += [f"- {e.name} → {', '.join(e.couplings)}" for e in coupled]
        out.append("")
    return "\n".join(out)
